name: Build and Publish NuGet Packages

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8'

      - name: Build and Publish NuGet Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet nuget add source --username Jinx-Laboratories --password ${{ secrets.NUGET_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Jinx-Laboratories/index.json"
          for d in $(find . -type f -name '*.csproj' -printf '%h\n' | sort -u); do
            cd $d
            dotnet build -c Release
            dotnet nuget push bin/Release/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_TOKEN }} --source github
            cd -
          done
