name: Build and Publish NuGet Packages

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
          
      - name: Update version in release branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout release
          version=$(git tag --list --points-at HEAD)
          sed -i.bak "s|<Version>.*</Version>|<Version>$version</Version>|" **/*.csproj
          git commit -a -m "Bump version to $version"
          git push

      - name: Build and Publish NuGet Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for d in $(find . -type f -name '*.csproj' -printf '%h\n' | sort -u); do
            cd $d
            dotnet pack -c Release
            dotnet nuget push bin/Release/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }}
            cd -
          done
